- build.sh
Preventing `*tcl*` accidentally resolving in an option (leading `-`)
Signed-off-by: TophEvich <84676511+TophEvich@users.noreply.github.com>
> build: prevent accidental glob-resolve into option

- build.sh
- src/main.py
- src/step2.sh
- src/stub.py
Add support for m1n1.bin and `kmutil --raw` for macOS. Avoiding OS version detection in `step2.sh` by copying either m1n1.macho or m1n1.bin. I did not want to spend time on that based on the assumption that pre 12.1 support will be dropped/hidden in the final installer.
> Add support for macos 12.1

- src/main.py
We do not want to support macOS 11.x and `step2.sh` does not work once the system recovery is updated to macOs 12.1 or later.
Remove macOS 12.0 beta as well since they are not signed anymore by Apple. Selecting those as startup disk requires changing the boot policy security mode to reduced security first.
> Remove unsupported macos versions

- build.sh
This fixes building the installer in macOS as the default python binary is python2 (included by macOS).
Moreover python2 is deprecated in macOS and the path forward is to specifically use python3 instead of the default python.
As far as I can see, pip (required to install certifi) is only available for python3 in homebrew.
> Force the use of python3

- src/firmware/__init__.py
Signed-off-by: Mark Kettenis <kettenis@openbsd.org>
> firmware: Use hard links in firmware tar files

- src/diskutil.py
With this disk layout:
diskutil list
/dev/disk0 (internal):
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:      GUID_partition_scheme                         500.3 GB   disk0
1:             Apple_APFS_ISC ⁨⁩                        524.3 MB   disk0s1
2:                 Apple_APFS ⁨Container disk3⁩         402.5 GB   disk0s2
(free space)                         91.9 GB    -
3:        Apple_APFS_Recovery ⁨⁩                        5.4 GB     disk0s6
/dev/disk3 (synthesized):
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:      APFS Container Scheme -                      +402.5 GB   disk3
Physical Store disk0s2
1:                APFS Volume ⁨Macintosh HD⁩            15.8 GB    disk3s1
2:              APFS Snapshot …
> diskutil.py: fix for empty Apple_APFS_RECOVERY

- src/osinstall.py
See Section 3 of RFC 4122: "The hexadecimal values "a" through "f" are
output as lower case characters ...". Simplifies handling of
"/chosen/asahi,efi-system-partition" in u-boot.
Signed-off-by: Janne Grunau <j@jannau.net>
> osinstall: Convert ESP partuuid to lower case

- src/install.sh
- Replace `dirname` call with builtin shell variable interpolation so the script works in recoveryOS
- Check for macOS >= 12 early to avoid confusing error messages in early versions of macOS 11
Fixes #114.
> Installer bootstrap script fixes (dirname + version check)

- asahi_firmware/update.py
- setup.py
Allows scripts and users to simply run the command `asahi-fwextract` instead of invoking the module with Python directly.
> asahi_fwextract: add console entrypoint

- asahi_firmware/multitouch.py
- src/main.py
- use 13.5 as only stub version, all others are downgraded to expert mode
- add missing devices (expert mode only)
- bump m1n1 to 1.3.0
- contains @WhatAmISupposedToPutHere touchbar firmware extraction from #173
- workaround for j415 trackpad plist (untested)
> Prepare installer for macOS 13.5

- asahi_firmware/img4.py
- asahi_firmware/kernel.py
This works as a replacement for img4tool with fewer dependencies.
> asahi_firmware.img4: Add an entrypoint

- src/diskutil.py
- src/main.py
- src/osenum.py
The Asahi Linux installer assumes a partition whose type is APFS is a container, but it sometimes turns otherwise because it is not formatted, for example.
Commit b550d86cf81d64449eff776d6b201245ff3ca9eb tried to solve the issue by filling `Partition.container` with a dictionary containing empty `Volumes` property. However, it broke some existing code checking if `Partition.container` is `None`. Particularly, it broke `InstallerMain.can_resize` which has such check, and accesses `CapacityFree` property.
It is difficult to fill `Partition.container` with a dummy dictionary containing lots of properties which an actual container can have, and it cannot prevent from perform some operation on the non-existing container.
This change removes the dummy dictionary and instead adds code to check …
> Check if a partition is a container

- src/osinstall.py
When installing m1n1, no package needs to be downloaded and the URL cache is None, triggering an exception when close_connection is called on it.
> Fix m1n1 installation (in expert mode)

- data/installer_data.json
Required after
https://pagure.io/fedora-asahi/kiwi-descriptions/c/ed3c8ba8c6d893de5b549308b6ba090d719b0eaf
Fixes: a908095 ("installer_data: Bump Fedora images to 202312190352")
> Bump Fedora Boot partition size to 1GiB

- src/main.py
In a previous commit from December 23, 2023, Hector removed the ability to install 12.4 even in expert mode.
https://github.com/AsahiLinux/asahi-installer/commit/8bbbb8ca5a347d99b243e10f24358573f1587df0
This suggests that the 12.4 IPSW is no longer necessary. Remove it.
> remove the 12.4 IPSW

- src/urlcache.py
In some corners of the world, you will experience connection problems installing Asahi Linux without a proxy. This adds basic HTTP proxy support to urlcache.py, honouring proxy settings from environment variables.
> urlcache: Support HTTP proxy

- asahi_firmware/img4.py
Upstream lzfse library has no SOVERSION set, but distributions with library packaging guidelines wants them.
Fedora[1] [2] is apparently already using SOVERSION 1 (and patching this file using sed on package builds). Debian[3] is about to do the same.
Try first to load liblzfse.so.1 and if not found, fall back on the unversioned soname as before. This should make everyone happy without having to patch it everywhere.
[1]: https://src.fedoraproject.org/rpms/lzfse/blob/rawhide/f/60.patch
[2]: https://src.fedoraproject.org/rpms/asahi-installer/blob/fb68ade87292d3210fbe8845da829add6b1187c4/f/asahi-installer.spec#_54
[3]: https://salsa.debian.org/bananas-team/lzfse/-/blob/debian/unstable/debian/patches/0001-debian-set-library-SONAME.patch
> asahi_firmware.img4: Try lzfse SOVERSION 1 first

- asahi_firmware/img4.py
In Fedora we unbundle `asn1` for `python-asahi_firmware` (which is the module installed on the system and used by `asahi-scripts`), this should make that work without having to patch the import.
> asahi_firmware: fallback to the system asn1

- data/installer_data.json
Please merge initially for the dev-installer to ease testing of KDE and Gnome builds as the installer_data.json from https://fedora-asahi-remix.org/builds.html have malformed `"extras"` rpm entries.
The KDE build installed successfully after manually fixing `"extras"` on M1.
We might not want to use this exact images as the image sizes increased by ~30% compared to Fedora 40.
> installer_data: Update to Fedora 41 (20241119)

- src/main.py
Observed in the wild on my machine:
> These users are machine admins: {' '.join(self.cur_os.admin_users)}
> Correctly interpolate machine admins in user string

- scripts/bootstrap-dev.sh
- scripts/bootstrap-prod.sh
- scripts/bootstrap.sh
I am using Dash for /bin/sh and the Asahi installer fails with "`Your version of cURL is too old`". This is because the curl check uses `&>/dev/null` which Dash does not support.  Updating to use the more compatible `>/dev/null 2>&1` instead.
```bash
> curl https://alx.sh | sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  2289  100  2289    0     0   4364      0 --:--:-- --:--:-- --:--:--  4368
Your version of cURL is too old. This usually means your macOS is very out
of date. Installing Asahi Linux requires at least macOS version 13.5.
> sw_vers
ProductName:		macOS
ProductVersion:		15.1.1
BuildVersion:		24B91
> what /bin/sh
/bin/sh:
PROGRAM:sh  PROJECT:dash-16
PROGRAM:sh  PROJECT:dash-16
> /bin/sh -c 'if ! …
```
> support Dash as /bin/sh

- src/util.py
PackageInstaller's fdcopy does not check if its `size` argument is zero before dividing `copied` by `size`. As a result, if non-image partitions in the installer package (typically, the ESP) contain empty files, copying those to disk raises a ZeroDivisionError that abruptly terminates the installation process, leaving it in an inconsistent state.
Check if `size` is different than zero, and if it is skip showing progress (which is totally fine and desired).
> Avoid dividing by zero when showing progress

- src/util.py
See: https://github.com/AOSC-Dev/aosc-asahi-installer/commit/c5c8633865c4369b14cade8bc2c1e43026d1207a, if rootfs image size can not multipie of 16MiB, asahi-installer will raise `EINVAL`, users don't know whats happen ...
The point of this commit is to look for illegitimate rootfs image sizes in advance, so that the raise error becomes clear.
> utils.py: raise error if rootfs file size is not multiple of 4KiB.

- src/util.py
The URL cache is only used in the (common) case where the installation zip archive is downloaded using http/https.
> Fix breakage when using local resources

- src/osinstall.py
Should solve #386. I have not been able to test it locally, as I do not have any Asahi Linux install to make now. It worked when tested on its own.
> discard/replace characters not part of the ASCII set for FAT partitions
